services:
  mysql:
    image: mysql:8.0
    container_name: dryfood-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dryfood_db
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
