spring.application.name=dryfood_myapp
server.port=8080

# ===== DATABASE CONFIG =====
spring.datasource.url=jdbc:mysql://localhost:3307/dryfood_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===== DEBUG ERROR =====
server.error.include-message=always
server.error.include-stacktrace=never

# ===== CẤU HÌNH OAUTH2 ĐĂNG NHẬP BẰNG GOOGLE =====
spring.security.oauth2.client.registration.google.client-id=869522607661-o6adv7fckvihjtqmqjft4vn02codj93o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:3000/oauth2/redirect

# ===== CẤU HÌNH BẢO MẬT JWT =====
jwt.secret=VGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1Qgc2lnbmluZyB3aXRoIEhTNTEy
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000

# ===== CORS CẤU HÌNH KẾT NỐI FRONTEND =====
app.cors.allowed-origins=http://localhost:3000,http://192.168.1.7:3000

# ===== JAVA MAIL SENDER =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130142@st.hcmuaf.edu.vn
spring.mail.password=ayxt qnhy glij thjx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== MOMO PAYMENT INTEGRATION =====
momo.partner.code=MOMOBKUN20180529
momo.access.key=klm05663944177542732
momo.secret.key=at Apr 11 17:15:05 ICT 2018
momo.api.url=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect.url=http://localhost:3000/
momo.notify.url=http://localhost:8080/api/v1/orders/momo-ipnpn
